server:
  port: 7050

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fhantoing/spring-api-microservices
          search-paths: configuracion-datos
        default-label: main
  application:
    name: configuracion-service